[ui]
editor = "hx"

[experimental-advance-branches]
enabled-branches = ["glob:*"]

[snapshot]
auto-update-stale = true

[aliases]
tug = ["bookmark", "move", "--from", "heads(::@- & bookmarks())", "--to", "@-"]

