[ -z "$PS1" ] && return
[[ -e $HOME/.profile ]] && source $HOME/.profile
source $DOTFILES/includes/zsh_first.zsh
ZSH_DEBUG=false
#ZSH_DEBUG=true
source $DOTFILES/includes/zshrc
source $DOTFILES/includes/zsh_last.zsh
