#!/usr/bin/env fish
# Snapshot current Tide universal variables to a file that can be committed.
# Run this after `tide configure` or manual Tide tweaks.

set -l script_dir (status dirname)
set -l out "$script_dir/tide-config.fish"

echo "# Auto-generated by save-tide-config.fish — do not edit by hand." >$out
echo "# Re-generate with: fish scripts/save-tide-config.fish" >>$out
echo "" >>$out

for name in (set -U --names | string match 'tide_*' | sort)
    set -l values $$name
    if test (count $values) -le 1
        echo "set -U $name $values" >>$out
    else
        set -l quoted
        for v in $values
            set -a quoted "'$v'"
        end
        echo "set -U $name $quoted" >>$out
    end
end

echo "Saved "(set -U --names | string match 'tide_*' | count)" Tide variables to $out"
