"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[mgr]
prepend_keymap = [
    { on = [ "g", "o" ], run = "shell --block '/var/home/rkj/dotfiles/personal/bin/yazi-repo-changes-view stack'", desc = "Show repo changes vs trunk" },
    { on = [ "g", "O" ], run = "shell --block '/var/home/rkj/dotfiles/personal/bin/yazi-repo-changes-view parent'", desc = "Show repo changes vs parent" },
]
